from queries import *
from connection import *
conn = create_connection()
def menu():
    print("----------------------------------------------------")
    print("Welcome to the Inventory Management System")
    print("----------------------------------------------------")
    print("1. Top 10 Products with Highest Revenue")
    print("2. Total Spending of Customers with Most Orders")
    print("3. Average Order Value of Customers by Region")
    print("4. Products with Highest Sales")
    print("5. Revenue Generated by Each Supplier")
    print("6. Revenue Generated by Discontinued Products")
    print("7. Products Frequently Purchased Together")
    print("8. Exit")

def user_choice():
    while True:
        menu()
        choice = input("Choose an option(1-8) : ")

        if choice == '1':
            highest_revenue_products()
        elif choice == '2':
            top_customers()
        elif choice == '3':
            avg_order_value_region()
        elif choice == '4':
            highest_sales_products()
        elif choice == '5':
            supplier_revenue()
        elif choice == '6':
            discontinued_product_sales()
        elif choice == '7':
            products_purchased_together()
        elif choice == '8':
            print("Exiting System !!!")
            close_connection(conn)
            break
        else:
            print("Invalid choice. Please choose an option between 1-8")

    